### PR TITLE
Add layout component for moderation panel

### LINKED ISSUE #466: Add layout components to Submission Portal page
## Problem:

We need to add the sections to host the components for the moderation panel.

## Success:

There are modular sections tied to the state of the page that will host the components for all of the moderation panel.

## Implementation Notes:

Lovely design:

Image

### PR DESCRIPTION
**Pull request by Anissa3005**
Resolves #466 

## 🔧 What changed

In this PR we have created the layout for the components of the moderation panel.

- Create components for modTopBar, modMainContainer and modLeftNavbar
- Create store for managing the state for switching between our dashboard screen an review submission screen
- Create the basic layout by adding basic styling

## 📸 Screenshots

image

### CODE REVIEW

**Comment by Anissa3005** [comment]
I have changed those in my latest commit, it should be there in the code. You also can see them in the screenshot.

**Review by ermish — APPROVED** [review]
great starting point

**Comment by NabbeunNabi** [comment]
I just pulled this merge. I think there is something missing that I found in the pull request from the logic. That we had from conditionally rendering the page in development. I will comment on the code

**Comment by theyokohamalife** [comment]
> I have changed those in my latest commit, it should be there in the code. You also can see them in the screenshot.

@Anissa3005 Nice work! It's okay here since the commits will all be squashed together, but it's good practice to have those changes together in the same commit so it makes it easier to review.

**Pull request merged**
