### PR TITLE
Added the portuguese json file and add the option

### PR DESCRIPTION
**Pull request by Diego-Bittencourt**
## 🔧 What changed
- Added the portuguese json file with all text in portuguese.

- Add the portuguese json file in the index.ts file to export it.

- Added the portuguese option in the mvpLocaleDisplayOptions type, in the localeStore.

- Changed from "Portuguese" to "Português" and switched from "Brazil" to "Brasil" in the localeDisplayOptions type in the store.

## 🧪 Testing instructions

Access the application, change the language settings to "Português" and note the text changes to words in portuguese.

## 📸 Screenshots

-   ### Before
image

-   ### After
image

### CODE REVIEW

**Review by ermish — APPROVED** [review]
Nice work! Thanks for helping us support a new language! 🙌🙌

**Comment by ermish** [comment]
The tests failing are unrelated so I think this is fine to merge. I'll merge when I get back home in an hour

**Comment by theyokohamalife** [comment]
@Diego-Bittencourt Thank you so much for the contribution! Could you rebase your branch off `main` to see if that will fix the tests?

**Review by theyokohamalife — CHANGES_REQUESTED** [review]
Looks good! Just need to rebase off main to see if that fixes CI.

**Review by theyokohamalife — APPROVED** [review]
LGTM ✨

**Pull request merged**
