### PR TITLE
add language dropdown

### LINKED ISSUE #58: Navbar - Create Locale Menu Dropdown
# Requirements

- Create a new vue dropdown component and integrate into the `TopNav` vue component
- Using vue best practices, wire up logic for opening and closing the menu based on local vue state. 
- You can use `English` and `Japanese` as temporary, hard-coded options in the menu for this PR. 
- UI should be responsive for when page changes width and should show in the hamburger menu

### PR DESCRIPTION
**Pull request by nasiranebi914**
Resolves #58

# What changed
Added a dropdown menu to select a language (English & Japaneses)

### CODE REVIEW

**Review by theyokohamalife — CHANGES_REQUESTED** [review]
Thank you for another contribution! Could you create a new component file and move the dropdown code into it? The components are kept inside of the `component/` directory. Then, you can use the component inside of the navbar.

There are a couple of eslint warnings that you can see in the comments above that will also need to be addressed before we can merge. Let us know if you need any help!

**Comment by ermish** [comment]
for the eslint warnings that @theyokohamalife mentioned, in your terminal, you can type `yarn lint --fix` and it might help fix these automatically ✨

**Comment by nasiranebi914** [comment]
Thank you @ann-kilzer @ermish @theyokohamalife for the advice! I have fixed the following:
- Create a new component named 'LocalSelector.vue' for the language dropdown 
- used 'yarn lint --fix' to fix the warnings
- Called the new component inside the 'TopNav.vue' 
- Removed default options, and kept only English/日本語

**Review by ann-kilzer — APPROVED** [review]
LGTM 🌟

**Review by theyokohamalife — APPROVED** [review]
Very nice! Thank you! 😎

**Pull request merged**
